
import type { Event } from './types';

export const allEvents: Event[] = [
  {
    id: '1',
    title: 'Summer Music Fest',
    description: 'Join us for a three-day music festival featuring the biggest names in pop, rock, and electronic music. Enjoy great food, art installations, and unforgettable performances under the sun.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    venue: 'Sunset Valley Fairgrounds',
    organizer: 'Vibes & Beats Co.',
    price: 150,
    imageId: 'event-music-fest',
    category: 'Music',
  },
  {
    id: '2',
    title: 'Future of AI Conference',
    description: 'A two-day conference exploring the latest advancements in Artificial Intelligence. Hear from industry leaders, researchers, and innovators shaping the future of technology.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    venue: 'Grand Tech Convention Center',
    organizer: 'Innovate AI',
    price: 499,
    imageId: 'event-tech-conference',
    category: 'Tech',
  },
  {
    id: '3',
    title: 'Gourmet Food & Wine Expo',
    description: 'Indulge your senses at the annual Gourmet Food & Wine Expo. Sample exquisite dishes from top chefs and taste fine wines from around theworld.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    venue: 'The Culinary Institute',
    organizer: 'TasteMakers Inc.',
    price: 75,
    imageId: 'event-food-expo',
    category: 'Food',
  },
  {
    id: '4',
    title: 'City Marathon 2024',
    description: 'Challenge yourself in the annual City Marathon. Run through the scenic streets of downtown and join thousands of fellow runners in this celebrated sporting event.',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    venue: 'Downtown Central Park',
    organizer: 'City Sports Commission',
    price: 50,
    imageId: 'event-marathon',
    category: 'Sports',
  },
  {
    id: '5',
    title: 'Modern Art Exhibition',
    description: 'Experience a stunning collection of contemporary art from emerging artists. The exhibition features paintings, sculptures, and interactive installations.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    venue: 'Metropolis Art Gallery',
    organizer: 'Creative Canvas',
    price: 25,
    imageId: 'event-art-exhibit',
    category: 'Art',
  },
  {
    id: '6',
    title: 'Indie Film Festival',
    description: 'Discover the next generation of filmmakers at our annual Indie Film Festival. Screenings of short films, documentaries, and feature films from around the globe.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    venue: 'The Golden Reel Cinema',
    organizer: 'CinemaVerse',
    price: 40,
    imageId: 'event-film-fest',
    category: 'Film',
  },
    {
    id: '7',
    title: 'Rock On! Concert',
    description: 'Get ready to rock with legendary bands and new-age rockstars. An evening of high-energy performances and classic hits.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    venue: 'The Rock Arena',
    organizer: 'Vibes & Beats Co.',
    price: 90,
    imageId: 'event-rock-concert',
    category: 'Music',
  },
  {
    id: '8',
    title: 'Startup Pitch Night',
    description: 'Witness the next big ideas as entrepreneurs pitch their startups to a panel of investors. Network with innovators and venture capitalists.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    venue: 'The Innovation Hub',
    organizer: 'Innovate AI',
    price: 20,
    imageId: 'event-startup-pitch',
    category: 'Tech',
  },
];

export const eventCategories = [
  'Music',
  'Tech',
  'Food',
  'Sports',
  'Art',
  'Film',
];
