
import type { Event } from './types';

export const allEvents: Event[] = [
  {
    id: '1',
    title: 'Diwali Festival of Lights',
    description: 'Celebrate the festival of lights with a spectacular display of fireworks, traditional music, and delicious Indian sweets.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    venue: 'India Gate, New Delhi',
    organizer: 'Incredible India Events',
    price: 500,
    imageId: 'event-diwali',
    category: 'Culture',
  },
  {
    id: '2',
    title: 'Holi Color Carnival',
    description: 'Join the most vibrant festival of colors. Dance to bollywood music, play with organic colors, and enjoy festive food.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    venue: 'Juhu Beach, Mumbai',
    organizer: 'Rang Barse Inc.',
    price: 800,
    imageId: 'event-holi',
    category: 'Music',
  },
  {
    id: '3',
    title: 'Mumbai International Film Festival',
    description: 'A week-long celebration of cinema, showcasing the best of Indian and international films. Premieres, workshops, and panel discussions with renowned filmmakers.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    venue: 'Film City, Mumbai',
    organizer: 'MIFF',
    price: 1500,
    imageId: 'event-film-fest-mumbai',
    category: 'Film',
  },
  {
    id: '4',
    title: 'Goa Sunburn Festival',
    description: 'Asia\'s largest electronic music festival. Experience world-class DJs, stunning visuals, and beach parties in beautiful Goa.',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    venue: 'Vagator Beach, Goa',
    organizer: 'Sunburn Events',
    price: 7500,
    imageId: 'event-sunburn-goa',
    category: 'Music',
  },
  {
    id: '5',
    title: 'Jaipur Literature Festival',
    description: 'The "greatest literary show on Earth". A confluence of the world\'s greatest writers, thinkers, and humanitarians.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    venue: 'Diggi Palace, Jaipur',
    organizer: 'Teamwork Arts',
    price: 1000,
    imageId: 'event-jaipur-lit',
    category: 'Art',
  },
  {
    id: '6',
    title: 'Bangalore Tech Summit',
    description: 'India\'s flagship technology event. Discover the latest in IT, biotech, and deep tech from global thought leaders and startups.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    venue: 'Bangalore Palace',
    organizer: 'Govt. of Karnataka',
    price: 3000,
    imageId: 'event-bangalore-tech',
    category: 'Tech',
  },
    {
    id: '7',
    title: 'Kochi-Muziris Biennale',
    description: 'An international exhibition of contemporary art held in Kochi, Kerala. It is the largest art exhibition in India.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    venue: 'Aspinwall House, Kochi',
    organizer: 'Kochi Biennale Foundation',
    price: 250,
    imageId: 'event-kochi-biennale',
    category: 'Art',
  },
  {
    id: '8',
    title: 'Street Food Festival Delhi',
    description: 'A paradise for food lovers. Taste authentic street food from all over India, from chaat and kebabs to chole bhature.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    venue: 'Jawaharlal Nehru Stadium, New Delhi',
    organizer: 'NASVI',
    price: 300,
    imageId: 'event-delhi-food',
    category: 'Food',
  },
];

export const eventCategories = [
  'Music',
  'Tech',
  'Food',
  'Art',
  'Film',
  'Culture',
];
