
import type { Event } from './types';

export const allEvents: Event[] = [
  {
    id: '4',
    title: 'Goa Sunburn Festival',
    description: 'Asia\'s largest electronic music festival. Experience world-class DJs, stunning visuals, and beach parties in beautiful Goa.',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    venue: 'Vagator Beach, Goa',
    organizer: 'Sunburn Events',
    price: 7500,
    imageId: 'event-sunburn-goa',
    category: 'Featured',
  },
  {
    id: '10',
    title: 'Indian Premier League (IPL) Final',
    description: 'Witness the electrifying final match of the biggest T20 cricket league in the world. A clash of titans for the ultimate glory.',
    date: new Date(new Date().setDate(new Date().getDate() + 60)).toISOString(),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    organizer: 'BCCI',
    price: 5000,
    imageId: 'event-ipl-final',
    category: 'Featured',
  },
    {
    id: '5',
    title: 'Jaipur Literature Festival',
    description: 'The "greatest literary show on Earth". A confluence of the world\'s greatest writers, thinkers, and humanitarians.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    venue: 'Diggi Palace, Jaipur',
    organizer: 'Teamwork Arts',
    price: 1000,
    imageId: 'event-jaipur-lit',
    category: 'Featured',
  },
  {
    id: '9',
    title: 'Chhath Puja on the Ganges',
    description: 'Experience the ancient Hindu Vedic festival dedicated to the Sun God, Surya. Devotees offer prayers and offerings on the banks of the Ganges.',
    date: new Date(new Date().setDate(new Date().getDate() + 50)).toISOString(),
    venue: 'Ganges River Ghats, Patna, Bihar',
    organizer: 'Bihar Tourism',
    price: 0,
    imageId: 'event-chhath-puja',
    category: 'Culture',
  },
  {
    id: '1',
    title: 'Diwali Festival of Lights',
    description: 'Celebrate the festival of lights with a spectacular display of fireworks, traditional music, and delicious Indian sweets.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    venue: 'India Gate, New Delhi',
    organizer: 'Incredible India Events',
    price: 500,
    imageId: 'event-diwali',
    category: 'Culture',
  },
  {
    id: '2',
    title: 'Holi Color Carnival',
    description: 'Join the most vibrant festival of colors. Dance to bollywood music, play with organic colors, and enjoy festive food.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    venue: 'Juhu Beach, Mumbai',
    organizer: 'Rang Barse Inc.',
    price: 800,
    imageId: 'event-holi',
    category: 'Music',
  },
  {
    id: '3',
    title: 'Mumbai International Film Festival',
    description: 'A week-long celebration of cinema, showcasing the best of Indian and international films. Premieres, workshops, and panel discussions with renowned filmmakers.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    venue: 'Film City, Mumbai',
    organizer: 'MIFF',
    price: 1500,
    imageId: 'event-film-fest-mumbai',
    category: 'Film',
  },
  {
    id: '6',
    title: 'Bangalore Tech Summit',
    description: 'India\'s flagship technology event. Discover the latest in IT, biotech, and deep tech from global thought leaders and startups.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    venue: 'Bangalore Palace',
    organizer: 'Govt. of Karnataka',
    price: 3000,
    imageId: 'event-bangalore-tech',
    category: 'Tech',
  },
  {
    id: '7',
    title: 'Kochi-Muziris Biennale',
    description: 'An international exhibition of contemporary art held in Kochi, Kerala. It is the largest art exhibition in India.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    venue: 'Aspinwall House, Kochi',
    organizer: 'Kochi Biennale Foundation',
    price: 250,
    imageId: 'event-kochi-biennale',
    category: 'Art',
  },
  {
    id: '8',
    title: 'Street Food Festival Delhi',
    description: 'A paradise for food lovers. Taste authentic street food from all over India, from chaat and kebabs to chole bhature.',
    date: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
    venue: 'Jawaharlal Nehru Stadium, New Delhi',
    organizer: 'NASVI',
    price: 300,
    imageId: 'event-delhi-food',
    category: 'Food',
  },
  {
    id: '21',
    title: 'Bihar Aam Mahotsav',
    description: 'A celebration of the king of fruits, the mango. Featuring hundreds of varieties of mangoes from across Bihar and India.',
    date: new Date(new Date().setDate(new Date().getDate() + 48)).toISOString(),
    venue: 'Gyan Bhawan, Patna, Bihar',
    organizer: 'Bihar Tourism',
    price: 50,
    imageId: 'event-aam-mahotsav',
    category: 'Food',
  },
  {
    id: '11',
    title: 'Pushkar Camel Fair',
    description: 'One of India\'s most famous traditional fairs. See thousands of camels, lively folk music and dance, and unique competitions.',
    date: new Date(new Date().setDate(new Date().getDate() + 45)).toISOString(),
    venue: 'Pushkar, Rajasthan',
    organizer: 'Rajasthan Tourism',
    price: 100,
    imageId: 'event-pushkar-fair',
    category: 'Culture',
  },
  {
    id: '12',
    title: 'Mysore Dasara',
    description: 'A 10-day festival in Mysore, ending with a grand procession of decorated elephants. A royal spectacle of culture and tradition.',
    date: new Date(new Date().setDate(new Date().getDate() + 22)).toISOString(),
    venue: 'Mysore Palace, Mysore',
    organizer: 'Govt. of Karnataka',
    price: 400,
    imageId: 'event-mysore-dasara',
    category: 'Culture',
  },
  {
    id: '13',
    title: 'Ziro Music Festival',
    description: 'An outdoor music festival in the breathtaking Ziro Valley of Arunachal Pradesh, showcasing indie music from across India.',
    date: new Date(new Date().setDate(new Date().getDate() + 35)).toISOString(),
    venue: 'Ziro Valley, Arunachal Pradesh',
    organizer: 'Ziro Events',
    price: 6000,
    imageId: 'event-ziro-music',
    category: 'Music',
  },
  {
    id: '14',
    title: 'Kolkata International Book Fair',
    description: 'The world\'s largest non-trade book fair. A haven for book lovers with stalls from national and international publishers.',
    date: new Date(new Date().setDate(new Date().getDate() + 70)).toISOString(),
    venue: 'Central Park Mela Ground, Kolkata',
    organizer: 'Publishers & Booksellers Guild',
    price: 50,
    imageId: 'event-kolkata-book-fair',
    category: 'Art',
  },
  {
    id: '15',
    title: 'Rann Utsav',
    description: 'Experience the white desert of Kutch under the full moon, with cultural performances, handicrafts, and adventure sports.',
    date: new Date(new Date().setDate(new Date().getDate() + 80)).toISOString(),
    venue: 'Dhordo, Kutch, Gujarat',
    organizer: 'Gujarat Tourism',
    price: 8000,
    imageId: 'event-rann-utsav',
    category: 'Culture',
  },
  {
    id: '16',
    title: 'NH7 Weekender Pune',
    description: 'India\'s happiest music festival featuring multiple stages with a lineup of Indian and international artists.',
    date: new Date(new Date().setDate(new Date().getDate() + 90)).toISOString(),
    venue: 'Mahalaxmi Lawns, Pune',
    organizer: 'OML',
    price: 4000,
    imageId: 'event-nh7-weekender',
    category: 'Music',
  },
  {
    id: '17',
    title: 'International Yoga Festival',
    description: 'A week-long celebration of yoga on the banks of the Ganges in the yoga capital of the world. Classes from world-renowned yoga masters.',
    date: new Date(new Date().setDate(new Date().getDate() + 55)).toISOString(),
    venue: 'Rishikesh, Uttarakhand',
    organizer: 'Parmarth Niketan Ashram',
    price: 2000,
    imageId: 'event-yoga-festival',
    category: 'Wellness',
  },
  {
    id: '18',
    title: 'Hornbill Festival',
    description: 'The "Festival of Festivals" in Nagaland, showcasing the rich cultural heritage of all the Naga tribes in one place.',
    date: new Date(new Date().setDate(new Date().getDate() + 100)).toISOString(),
    venue: 'Naga Heritage Village, Kisama',
    organizer: 'Govt. of Nagaland',
    price: 200,
    imageId: 'event-hornbill-festival',
    category: 'Culture',
  },
  {
    id: '19',
    title: 'India Art Fair',
    description: 'South Asia\'s leading platform for modern and contemporary art. Discover works from leading galleries and artists.',
    date: new Date(new Date().setDate(new Date().getDate() + 65)).toISOString(),
    venue: 'NSIC Exhibition Grounds, New Delhi',
    organizer: 'India Art Fair',
    price: 700,
    imageId: 'event-india-art-fair',
    category: 'Art',
  },
  {
    id: '20',
    title: 'Great Indian Food Festival',
    description: 'Embark on a culinary journey across India. Featuring over 100 stalls with regional delicacies and live cooking demonstrations.',
    date: new Date(new Date().setDate(new Date().getDate() + 12)).toISOString(),
    venue: 'DLF CyberHub, Gurgaon',
    organizer: 'Foodie\'s Hub',
    price: 500,
    imageId: 'event-indian-food-fest',
    category: 'Food',
  }
];

export const eventCategories = [
  'Music',
  'Tech',
  'Food',
  'Art',
  'Film',
  'Culture',
  'Sports',
  'Wellness',
  'Featured'
];
